env:
  browser: true
  es2021: true
  jest: true

globals:
  test: true
  expect: true

parser: "@babel/eslint-parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  requireConfigFile: false
  babelOptions:
    presets:
      - "@babel/preset-react"

extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb-base

plugins:
  - react
  - react-hooks
  - jest

rules:
  import/extensions: 0
  no-console: 0
  react/prop-types: off
  react/jsx-indent: [2, 2]
  react/jsx-indent-props: [2, 2]
  react/jsx-closing-bracket-location: 2
  react/destructuring-assignment: 2
  react/jsx-wrap-multilines: 2

settings:
  react:
    version: detect
    